---
- name: copy redis config
  template:
    src: etc/redis.conf.j2
    dest: /etc/redis.conf
    owner: root
    group: root
    mode: 0666
    backup: yes

- name: enable and start redis on boot
  service:
    name: redis
    enabled: yes
    state: started
