---

dependencies:
  - role: adfinis-sygroup.pki

galaxy_info:
  author: 'Adfinis SyGroup AG'
  description: 'Install and configure nginx with virtualhosts'
  company: 'Adfinis SyGroup AG'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - nginx
    - webserver
    - http
    - httpd
    - proxy
