---
 - name: start apache
   service:
     name: '{{ apache_servicename }}'
     enabled: true

 - name: configure firewall to allow http/https
   firewalld:
     state: enabled
     service: '{{ item }}'
     permanent: true
   with_items:
     - http
     - https 
