- hosts: mattermost
  roles:
     - { role: epel, tags: epel }
     - { role: adfinis-sygroup.nginx, tags: nginx }
     - { role: adfinis-sygroup.mariadb, tags: mariadb }
     - { role: mattermost, tags: mattermost }

- hosts: nextcloud
  roles:
     - { role: epel, tags: epel }
     - { role: adfinis-sygroup.mariadb, tags: mariadb }
     - { role: apache, tags: apache }
     - { role: php7, tags: php7 }
     - { role: nextcloud, tags: nextcloud }

- hosts: ldap
  roles:
     - { role: ldapuser, tags: ldapuser }

- hosts: lool
  roles:
     - { role: lool, tags: lool }

- hosts: redis
  roles:
     - { role: epel, tags: epel }
     - { role: redis, tags: redis }

- hosts: redis_sentinel
  roles:
     - { role: epel, tags: epel }
     - { role: redis_sentinel, tags: redis_sentinel }
