---

- name: nginx check config
  command: '{{ nginx_binary }} -t'

- name: nginx check config and reload
  command: '{{ nginx_binary }} -t'
  notify:
    - 'nginx reload daemon'

- name: nginx check config and restart
  command: '{{ nginx_binary }} -t'
  notify:
    - 'nginx restart daemon'

- name: nginx restart daemon
  service:
    name: '{{ nginx_service }}'
    state: restarted

- name: nginx reload daemon
  service:
    name: '{{ nginx_service }}'
    state: reloaded

- name: nginx remove default vhost
  file:
    path: '{{ nginx_default_vhost }}'
    state: absent
