---
- name: enable selinux
  selinux:
    policy: targeted
    state: enforcing

- name: reboot the machine to enable selinux
  reboot:

- name: wait for server to come back
  become: false
  local_action:
    module: wait_for
      host={{ ansible_host }}
      port=22
      delay=2
      state=started

- name: allow sentinel to listen on tcp ports
  seport:
    ports: 26379
    proto: tcp
    setype: redis_port_t
    state: present

# set to permissive, because without a proper policy the sentinel
# reconfiguration script is not executable
- selinux_permissive:
    name: redis_t
    permissive: true
