---
 - name: generate data directory
   file:
     path: '{{ nextcloud_install_dir }}/nextcloud/data'
     setype: httpd_sys_rw_content_t
     owner: '{{ httpd_user }}'
     group: '{{ httpd_group }}'
     state: directory

 - name: selinux contexts for nextcloud
   file: 
     path: '{{ nextcloud_install_dir }}/{{ item }}' 
     setype: httpd_sys_rw_content_t
     owner: '{{ httpd_user }}'
     group: '{{ httpd_group }}'
   with_list: '{{ nextcloud_selinux_paths }}'

 - name: apache site configuraiton for nextcloud
   template:
     src: nextcloud.conf.j2
     setype: httpd_sys_rw_content_t
     dest: '{{ httpd_site_conf_path }}/nextcloud.conf'
     owner: '{{ httpd_user }}'
     group: '{{ httpd_group }}'
   notify: reload_httpd

 - name: db configuration for nextcloud
   template:
     src: config.php.j2
     dest: '{{ nextcloud_install_dir }}/nextcloud/config/config.php'
     setype: httpd_sys_rw_content_t
     owner: '{{ httpd_user }}'
     group: '{{ httpd_group }}'
     force: no 
    
 - name: make occ executable
   file:
     path: '{{ nextcloud_install_dir }}/nextcloud/occ'
     mode: 0755
     owner: '{{ httpd_user }}'
     group: '{{ httpd_group }}'
     setype: httpd_sys_rw_content_t

 - name: enable ldap backend
   become: true
   become_user: '{{ httpd_user }}'
   command: "/opt/rh/rh-php70/root/bin/php '{{ nextcloud_install_dir }}'/nextcloud/occ app:enable user_ldap"

 - name: enable ldap backend
   become: true
   become_user: '{{ httpd_user }}'
   command: "/opt/rh/rh-php70/root/bin/php '{{ nextcloud_install_dir }}'/nextcloud/occ app:enable user_ldap"

 - name: read ldap config
   become: true
   become_user: '{{ httpd_user }}'
   command: "/opt/rh/rh-php70/root/bin/php '{{ nextcloud_install_dir }}'/nextcloud/occ ldap:show-config" 
   register: nextcloud_ldap_config_query
   failed_when: false
   changed_when: false

 - name: debug 
   debug:
     var: nextcloud_ldap_config
   
 - name: create ldap config s01
   become: true
   become_user: '{{ httpd_user }}'
   command: "/opt/rh/rh-php70/root/bin/php '{{ nextcloud_install_dir }}'/nextcloud/occ ldap:create-empty-config"  
   when: not "s01" in nextcloud_ldap_config_query.stdout_lines
    

 - name: apply config setting for ldap configuration
   become: true
   become_user: '{{ httpd_user }}'
   command: "/opt/rh/rh-php70/root/bin/php {{ nextcloud_install_dir }}/nextcloud/occ ldap:set-config s01 {{ item.key }} {{ item.value.entry }}"  
   with_dict: "{{ nextcloud_ldap_config }}"

 - name: allow access to ldap server selinux
   command: setsebool -P httpd_can_connect_ldap on

 - name: allow network access to HTTPS in firewalld
   firewalld:
     service: https
     permanent: true
     state: enabled
