--- 
 - name: create ssl private directory
   file:
     path: '{{ httpd_ssl_cert_path }}'
     owner: '{{ httpd_user }}'
     group: '{{ httpd_group }}'
     setype: httpd_sys_rw_content_t 
     state: directory

 - name: copy ssl certs to path
   copy:
     src: 'files/{{ httpd_ssl_cert_name }}'
     dest: '{{ httpd_ssl_cert_path }}/{{ httpd_ssl_cert_name }}'
     owner: '{{ httpd_user }}'
     group: '{{ httpd_group }}'
     setype: httpd_sys_rw_content_t 
   notify: reload_httpd

 - name: copy ssl certs to path
   copy:
     src: 'files/{{ httpd_ssl_key_name }}'
     dest: '{{ httpd_ssl_cert_path }}/{{ httpd_ssl_key_name }}'
     owner: '{{ httpd_user }}'
     group: '{{ httpd_group }}'
     setype: httpd_sys_rw_content_t 
   notify: reload_httpd

