---

 - name: enabling masquerading in firewalld
   firewalld:
     masquerade: yes
     state: enabled
     permanent: true
     zone: public

 - name: redirect port 443 to loolwsd port
   firewalld:
     rich_rule: rule family={{ item }} forward-port port=443 protocol=tcp to-port={{ lool_port }}
     zone:      public
     permanent: true
     immediate: true
     state:     enabled
   with_items:
     - ipv4

 - name: enabling firewalld service
   service:
     name: firewalld
     enabled: yes
     state: started

 - name: crate logfile
   file:
     path: /var/log/loolwsd.log
     owner: lool
     group: lool
     mode: 0660

 - name: lool configuration
   template:
     src: loolwsd.xml.j2
     dest: '{{ lool_conf_path }}/loolwsd.xml'
     owner: '{{ lool_user }}'
     group: '{{ lool_group }}'
   notify: restart_loolwsd

 - name: enabling loolwsd service
   service:
     name: loolwsd
     enabled: yes
     state: started

 - name: configure selinux to permissive
   selinux:
     policy: targeted
     state: permissive

 - name: ensure SELinux is turned off until the next reboot
   action: command /usr/sbin/setenforce 0
   ignore_errors: yes
