---

 - name: add collaboraoffice repo
   yum_repository:
     name: collaboraoffice
     description: Collabora Online
     gpgkey: 'https://collaboraoffice.com/repos/CollaboraOnline/3/customer-centos7-{{ lool_customer_hash }}/repodata/repomd.xml.key'
     baseurl: 'https://collaboraoffice.com/repos/CollaboraOnline/3/customer-centos7-{{ lool_customer_hash }}'

 - name: install collabora online packages
   package:
     name: '{{ item }}'
     state: latest
   with_items:
     - loolwsd
     - collabora-online-brand
     - collaboraoffice*de*
     - collaboraoffice*fr*
     - collaboraoffice*it*
     - collaboraoffice5.3-dict-de
     - collaboraoffice5.3-dict-fr
     - collaboraoffice5.3-dict-it
     - collaboraoffice5.3-dict-en
     - hunspell-de
     - hunspell-fr
     - hunspell-it
     - hunspell-en*

 - name: linking /usr/share/myspell to /usr/share/hunspell for dicts to work
   file:
     src: /usr/share/myspell
     dest: /usr/share/hunspell
     state: link

