---
 - name: configure mattermost vhost template
   template:
     src: mattermost.conf.j2
     dest: /etc/nginx/conf.d/mattermost.conf
     owner: root
     group: root
   notify: reload_httpd

 - name: install mattermost licsense 
   copy:
     src: 'files/{{ mattermost_licsense_name }}'
     dest: '{{ mattermost_user_home }}/config/{{ mattermost_licsense_name }}'
   notify: mattermost_restart
   when: mattermost_licsense_name is defined

 - name: configure application template
   template:
     src: config.json.j2
     dest: '{{ mattermost_user_home }}/config/config.json'
   notify: mattermost_restart

 - name: install certificates for sso broker
   copy:
     src: '{{ item }}'
     dest: '{{ mattermost_user_home }}/config/{{ item }}'
     owner: '{{ mattermost_user_name }}'
     group: '{{ mattermost_group_name }}'
     mode: 0640
   with_items: 
     - '{{ mattermost_broker_cert_key }}'
     - '{{ mattermost_ssl_public_cert }}'
     - '{{ mattermost_ssl_private_key }}'
   notify: mattermost_restart

 - name: systemd application file
   template:
     src: mattermost.service.j2
     dest: /etc/systemd/system/mattermost.service
     mode: 0644
     owner: root
     group: root 
   notify: mattermost_restart 

 - name: start mattermost
   service: 
     name: mattermost
     state: started
     enabled: true

 - name: enable firewall for mattermost
   firewalld:
     service: '{{ item }}'
     state: enabled
     permanent: true
   with_items:
     - http
     - https

 - name: enable firewall for mattermost
   firewalld:
     port: '{{ mattermost_listen_port }}/tcp'
     state: enabled
     permanent: true
