--- 
 - name: create application group
   group:
     name: '{{ mattermost_group_name }}'

 - name: Create Mattermost user
   user:
     name: '{{ mattermost_user_name }}'
     comment: 'mattermost user'
     createhome: true
     group: '{{ mattermost_group_name }}' 
     home: '{{ mattermost_user_home }}'

 - name: download application source
   get_url: 
     url: "{{ mattermost_releases_url }}{{ mattermost_version}}/mattermost-{{ mattermost_version }}-linux-amd64.tar.gz"
     dest: "/opt/mattermost-{{ mattermost_version }}-linux-amd64.tar.gz"

 - name: unpack application
   unarchive: 
     src: '/opt/mattermost-{{ mattermost_version }}-linux-amd64.tar.gz'
     dest: '/opt/'
     remote_src: yes 
     creates: '/opt/mattermost/bin/mattermost'

 - name: give group rights to homedirectory
   file:
     path: '{{ mattermost_user_home }}'
     owner: '{{ mattermost_user_name }}'
     group: '{{ mattermost_group_name }}'
     mode: 'g+w'
     recurse: true

 - name: create datadirectory
   file: 
     path: '{{ mattermost_user_home }}/data'
     owner: '{{ mattermost_user_name }}'
     group: '{{ mattermost_group_name }}'
     state: directory
