--- 
 - name: create application group
   group:
     name: '{{ mattermost_group_name }}'

 - name: Create Mattermost user
   user:
     name: '{{ mattermost_user_name }}'
     comment: 'mattermost user'
     createhome: true
     group: '{{ mattermost_group_name }}' 
     home: '{{ mattermost_user_home }}'

 - name: download and unpack application source
   get_url: 
     url: "{{ mattermost_releases_url }}/{{ mattermost_version }}-linux-amd64.tar.gz"
     dest: "/opt/mattermost-{{ mattermost_version }}-linux-amd64.tar.gz"
     remote_src: yes 

 - name: unpack application
   archive: 
     path: '/opt/mattermost-5.0.0-linux.amd64.tar.gz'
     dest: '{{ mattermost_user_home }}'

 - name: give group rights to homedirectory
   file:
     path: '{{ mattermost_user_home }}'
     owner: '{{ mattermost_user_name }}'
     group: '{{ mattermost_group_name }}'
     mode: 'g+w'
     recurse: true

 - name: create datadirectory
   file: 
     path: '{{ mattermost_user_home }}/data'
     owner: '{{ mattermost_user_name }}'
     group: '{{ mattermost_group_name }}'
     state: directory
