---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::mattermost'
    - 'role::mattermost:install'
    - 'role::mattermost:config'

- import_tasks: installation.yml
  tags:
    - 'role::mattermost'
    - 'role::mattermost:install'

- import_tasks: configuration.yml
  tags:
    - 'role::mattermost'
    - 'role::mattermost:config'

- import_tasks: sslconfig.yml
  tags:
    - 'role::mattermost'
    - 'role::mattermost:config'
 
