---
- name: include os specific vars
  include_vars: '{{ item }}'

  with_first_found:
    - files:
        - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
  tags:
    - 'role::keepalived'
    - 'role::keepalived:install'
    - 'role::keepalived:config'

- import_tasks: installation.yml
  tags:
    - 'role::keepalived'
    - 'role::keepalived:install'

- import_tasks: configuration.yml
  tags:
    - 'role::keepalived'
    - 'role::keepalived:config'
