---

# mariadb related packages
mariadb_packages:
  - rh-mariadb102
  - rh-mariadb102-mariadb-server
  - MySQL-python
  - pwgen
  - pyOpenSSL

# mariadb service name
mariadb_service: rh-mariadb102-mariadb

# mariadb user
mariadb_user: mariadb

# mariadb server binary
mariadb_server_bin: /opt/rh/rh-mariadb102/root/usr/libexec/mysqld

# global mariadb configuration file location
mariadb_conf: /etc/my.cnf

# global mariadb configuration directory
mariadb_conf_dir: /etc/mariadb/conf.d

# mariadb configuration files
mariadb_conf_files:
  - client
  - server
  - mysqld_safe
  - mysqldump

# roots my.cnf
mariadb_root_mycnf: /root/.my.cnf

# mariadb slow log file
mariadb_log_slow: /var/log/mariadb/mariadb-slow.log

# mariadb error log file
mariadb_log_error: /var/log/mariadb/mariadbd.err

# mariadb run directory
mariadb_run_dir: /var/run/rh-mariadb102-mariadb

# mariadb socket file
mariadb_socket: '/var/lib/mysql/mysql.sock'

# mariadb anonymous users
mariadb_anon_user_hosts:
  - localhost
  - '{{ ansible_fqdn }}'

# mariadb pki path
mariadb_pki_path: /etc/pki/mariadb

# MariaDB default character set.
mariadb_character_set_default: utf8mb4
